blogapp/main/routes.py
from flask import Blueprint, render_template, request, flash
from blogapp.models import Post,User
from blogapp.main.form import contactForm
from blogapp import mail
from flask_mail import Message
from flask_login import login_required, current_user

main = Blueprint('main', __name__)


@main.route('/')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('index.html', posts=posts)


@main.route('/about')
@login_required
def about():
    return render_template('about.html')


@main.route('/gallery')
@login_required
def gallery():
    return render_template('gallery.html')


@main.route('/contact', methods=['GET', 'POST'])
@login_required
def contact():
    user = User
    form = contactForm()
    if form.validate_on_submit():
        msg = Message(f'New Message from {current_user.username}', sender=f'{user.email}',
                      recipients=['wishotstudio@gmail.com'])
        msg.body = f"""
           Name :  {form.name.data}

           Email :  {form.contact_email.data}

           Subject :  {form.subject.data}

           Message :  {form.message.data}
           """
        mail.send(msg)
        flash('your message have been sent', 'success')

    return render_template('contact.html', title='contact Form', form=form)

blogapp/post/routes.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, abort
from flask_login import login_required, current_user
from blogapp import db
from blogapp.models import Post
from blogapp.post.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route('/post', methods=['POST', 'GET'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('your Post Has Been Created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('control.html', title='New Post', legend='New post', form=form)


@posts.route('/post-<int:post_id>', methods=['POST', 'GET'])
def single(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('single-post.html', title=post.title, post=post)


@posts.route('/post-<int:post_id>-update', methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your Post Has Been Updated!", "success")
        return redirect(url_for('posts.single', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('control.html', title='Update Post', legend='update post', form=form)


@posts.route('/post-<int:post_id>-delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your Post Has Been Deleted!", "success")
    return redirect(url_for('main.home'))

blogapp/user/routes.py
from flask import Blueprint, redirect, request, render_template, flash, url_for
from flask_login import login_required, current_user, logout_user, login_user
from blogapp import db, bcrypt
from blogapp.user.utils import save_picture
from blogapp.user.utils import send_password_reset_email
from blogapp.models import Post, User
from blogapp.user.forms import LoginForm, RegistrationForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password=hashed_password)
            db.session.add(user)
            db.session.commit()
            flash(f"Account created for {form.username.data}!.", 'success')
            return redirect(url_for('users.login'))
    return render_template('register.html', title=register, form=form)


@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('Login Successful', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, please check your Email And Password', 'danger')
    return render_template('login.html', title=login, form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your Account Has Been Updated", "success")
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', form=form, image_file=image_file)


@users.route("/user-<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
    return render_template('user_post.html', posts=posts, user=user)


@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password-<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"your password has been updated!.", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

blogapp/templates/Register.html
{% extends 'layout.html' %}

{% block content   %}
<div class="blog-comment p-5">
    <form method="POST" action="" style="margin: 20px;width: 75%; margin: auto">
       {{ form.hidden_tag() }}
        <fieldset class="form-group m-3">
            <legend class="border-bottom mb-5 text-info"> Join Us Today</legend>
            <div class="form-group">
                {{ form.username.label(class= "form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.username.errors %}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else%}
                     {{ form.username(class= "form-control form-control-lg") }}
                {% endif%}
            </div>

            <div class="form-group">
                {{ form.email.label(class= "form-control-label") }}
               {% if form.email.errors %}
                   {{ form.email(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.email.errors%}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else %}
                     {{ form.email(class= "form-control form-control-lg") }}
                {% endif%}
            </div>

            <div class="form-group">
                {{ form.password.label(class= "form-control-label") }}
                {% if form.password.errors %}
                   {{ form.password(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.password.errors %}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else%}
                     {{ form.password(class= "form-control form-control-lg") }}
                {% endif%}
            </div>

            <div class="form-group">
                {{ form.confirm_password.label(class= "form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.confirm_password.errors%}
                            <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else%}
                     {{ form.confirm_password(class= "form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
        <div class="form-group">
        {{ form.submit( class="btn btn-outline-info bg-primary" ) }}
        </div>
    </form>

    <div class="border-top pt-2" style="width: 75%; margin: auto">
      <small class="text-muted">
         Already Have An Account? <a class="ml-3 text-primary" href= "{{ url_for('users.login') }}">Sign In </a>
      </small>
   </div>
</div>

{% endblock content  %}

blogapp/templates/account.html
{% extends 'layout.html' %}

{% block content %}
<div class="content-section">
  <div class="median ment">
     <img class="round-circle account-img" src="{{ image_file }}">
       <div class="media-body">
          <h2 class="account-heading"> {{current_user.username}}</h2>
           <P class="text-secondary"> {{current_user.email}}</P>
        </div>
  </div>
   <div class="blog-comment p-5">
     <form method="POST" action="" style="margin: 20px;width: 75%; margin: auto" enctype="multipart/form-data">
       {{ form.hidden_tag() }}

        <fieldset class="form-group m-3">
            <legend class="border-bottom mb-5 text-info"> Account Info </legend>
            <div class="form-group">
                {{ form.username.label(class= "form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.username.errors %}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else%}
                     {{ form.username(class= "form-control form-control-lg") }}
                {% endif%}
            </div>

            <div class="form-group">
                {{ form.email.label(class= "form-control-label") }}
               {% if form.email.errors %}
                   {{ form.email(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.email.errors%}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else %}
                     {{ form.email(class= "form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
           <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class= "form-control-file") }}
               {% if form.picture.errors %}
                 {% for error in form.picture.errors%}
               <span class="alert-danger"> {{ error }} </span> </br>
                 {% endfor %}
               {% endif %}
            </div>

         <div class="form-group" style="padding-top: 20px">
            {{ form.submit( class="btn btn-outline-info bg-primary" ) }}
             <span class="post"> <a href="{{url_for('posts.new_post') }}"> Create Post</a></span>
        </div>
     </form>
   </div>
</div>
{% endblock content %}

blogapp/templates/index.html
{% extends "layout.html" %}

{% block content %}

<!-- Home Section -->

<section id="home" class="main-home parallax-section">
     <div class="overlay"></div>
     <div id="particles-js"></div>
     <div class="container">
          <div class="row">

               <div class="col-md-12 col-sm-12">
                    <h1>Hello! This is Wishot.</h1>
                    <h4>Finding  Your Nearest Photographer</h4>
                    <a href="{{url_for('main.gallery')}}" class="smoothScroll btn btn-default">Discover More</a>
               </div>

          </div>
     </div>
</section>

<!-- Blog Section -->

<section id="blog">
         {% for post in posts.items %}
    <div class="container">
         <div class="col-md-offset-1 col-md-10 col-sm-12">
                  <div class="blog-post-thumb">
<!--                         <div class="blog-post-image">-->
<!--                              <a href="{{url_for('posts.single', post_id=post.id)}}">-->
<!--                                  <img src="{{image_content}}" class="img-responsive" alt="Blog Image">-->
<!--                              </a>-->
<!--                         </div>-->
                         <div class="blog-post-format">
                              <span><a href="{{ url_for('users.user_posts', username=post.author.username)}}"><img src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}" class="img-responsive img-circle" style=" width: 55px;"> {{ post.author.username }}</a></span>
                              <span><i class="fa fa-date"></i> {{ post.date_posted.strftime( ' %d %b %Y') }}</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 35 </a></span>
                             <div class="blog-post-title">
                               <h3> Title: <a href="{{ url_for('posts.single', post_id=post.id)}}">{{ post.title }} </a></h3>
                            </div>
                         </div>
                         <div class="blog-post-des">
                              <p>{{post.content}}</p>
                              <a href="{{ url_for('posts.single',post_id=post.id)}}" class="btn btn-default">Continue Reading</a>
                         </div>
                  </div>
          </div>
        </div> <hr style="border-color: #8c8c8c">

</section>


     {% endfor %}

     {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
               {% if posts.page == page_num %}
                   <a  class="btn btn-danger mb-4" href="{{ url_for('main.home', page=page_num) }}"> {{page_num}} </a>
               {% else %}
             <a  class="btn btn-success mb-4" href="{{ url_for('main.home', page=page_num) }}"> {{page_num}} </a>
               {% endif %}
          {% else %}
               ...
          {% endif %}
     {% endfor %}
<!-- Footer Section -->

{% endblock content %}

blogapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<title>Wishot Studio</title>
<!--

Template 2085 wishot

http://www.tooplate.com/view/2085-neuron

-->
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<!--     <link rel="stylesheet" href="static/css/bootstrap.min.css">-->
<link rel="stylesheet" href="static/css/font-awesome.min.css">

<!-- Main css -->
<link rel="stylesheet" href="static/css/style.css">
<link href="https://fonts.googleapis.com/css?family=Lora|Merriweather:300,400" rel="stylesheet">

</head>
<body>

<!-- PRE LOADER -->


<div class="preloader">
     <div class="sk-spinner sk-spinner-wordpress">
          <span class="sk-inner-circle"></span>
     </div>
</div>

<!-- Navigation section  -->

<div class="navbar navbar-default navbar-static-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>
               <a href="{{url_for('main.home')}}" class="navbar-brand">WISHOT</a><img src="static/images/logo2.jpg" class="img-responsive photo" alt="">

          </div>
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-right">
                    {% if current_user .is_authenticated %}
                    <li><a href="{{ url_for('users.account') }}">Account</a></li>
                    <li class="active"><a href="{{ url_for('main.home') }}">Home</a></li>
                    <li onclick=" add.className='active'"><a href="{{ url_for('main.about') }}">About</a></li>
                    <li><a href="{{ url_for('main.gallery') }}">Gallery</a></li>
                    <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
                    <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                    <li><a href="{{ url_for('users.register') }}">register</a></li>
                    <li><a href="{{ url_for('users.login') }}">Login</a></li>
                    {% endif %}

               </ul>
          </div>

  </div>
</div>

<!-- Home Section -->
{% with messages = get_flashed_messages(with_categories=true) %}
 {% if messages %}
   {% for category, message in messages %}
     <div class="alert alert-{{ category }}">
      {{ message }}
     </div>
   {% endfor %}
 {% endif %}
{% endwith %}

{% block content %}
{% endblock content %}

<!-- Footer Section -->

<footer>
     <div class="container">
          <div class="row">

               <div class="col-md-5 col-md-offset-1 col-sm-6">
                    <h3>Wishot Studio</h3>
                    <p>Bent on serving you and providing you with beautiful photographs and studio workers/photographers.</p>
                    <div class="footer-copyright">
                         <p>Copyright &copy; 2022 Wishot Studio - Designs</p>
                    </div>
               </div>

               <div class="col-md-4 col-md-offset-1 col-sm-6">
                    <h3>Talk to us</h3>
                    <p><i class="fa fa-globe"></i> Coal City, Enugu Nigeria </p>
                    <p><i class="fa fa-phone"></i> 081-0544-4154</p>
                    <p><i class="fa fa-save"></i> info@company.com</p>
               </div>

               <div class="clearfix col-md-12 col-sm-12">
                    <hr>
               </div>

               <div class="col-md-12 col-sm-12">
                    <ul class="social-icon">
                        <li><a href="https://www.facebook.com/wisdom.alom.3" class="fa fa-facebook"></a></li>
                         <li><a href="https://mobile.twitter.com/wisdom53170998" class="fa fa-twitter"></a></li>
                         <li><a href="mailto:wishotstudio@gmail.com" class="fa fa-google-plus"></a></li>
                         <li><a href="https://github.com/Crypwise" class="fa fa-github"></a></li>
                         <li><a href="https://www.linkedin.com/in/wisdom-obumneme-3a2033242" class="fa fa-linkedin"></a></li>
                    </ul>
               </div>

          </div>
     </div>
</footer>

<!-- Back top -->
<a href="#back-top" class="go-top"><i class="fa fa-angle-up"></i></a>

<!-- SCRIPTS -->

<script src="static/js/jquery.js"></script>
<script src="static/js/bootstrap.min.js"></script>
<script src="static/js/particles.min.js"></script>
<script src="static/js/app.js"></script>
<script src="static/js/jquery.parallax.js"></script>
<script src="static/js/smoothscroll.js"></script>
<script src="static/js/custom.js"></script>

</body>
</html>

blogapp/templates/login.html
{% extends 'layout.html'%}

{% block content   %}
<div class="blog-comment p-5">
    <form method="POST" action="" class="p-5 " style="padding: 20px;width: 75%; margin: auto">
       {{ form.hidden_tag() }}

        <fieldset class="form-group m-3">
            <legend class="border-bottom mb-5 text-info"> Login Today</legend>
            <div class="form-group">
                {{ form.email.label(class= "form-control-label") }}
               {% if form.email.errors %}
                   {{ form.email(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.email.errors%}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else %}
                     {{ form.email(class= "form-control form-control-lg") }}
                {% endif%}
            </div>

            <div class="form-group">
                {{ form.password.label(class= "form-control-label") }}
                {% if form.password.errors %}
                   {{ form.password(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.password.errors %}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else%}
                     {{ form.password(class= "form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
            <div class="form-check">
                {{form.remember( class=" form-check-input ")}}
                {{form.remember.label( class=" form-check-label ")}}
            </div>
        <div class="form-group">
        {{ form.submit( class="btn btn-outline-info bg-primary" ) }}
              <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}"> Forgot Password? </a>
            </small>
        </div>
    </form>

    <div class="border-top pt-2" style="width: 75%; margin: auto">
      <small class="text-muted">
         Do Not Have An Account? <a class="ml-3 text-primary" href= "{{ url_for('users.register') }}">Sign up </a>
      </small>
    </div>
</div>
{% endblock content %}

blogapp/templates/reset_request.html
{% extends 'layout.html'%}

{% block content   %}
<div class="blog-comment p-5">
    <form method="POST" action="" class="p-5 " style="padding: 20px;width: 75%; margin: auto">
       {{ form.hidden_tag() }}

        <fieldset class="form-group m-3">
            <legend class="border-bottom mb-5 text-info"> Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class= "form-control-label") }}
               {% if form.email.errors %}
                   {{ form.email(class= "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                         {% for error in form.email.errors%}
                           <span class="alert-danger"> {{ error }} </span>
                         {% endfor%}
                    </div>
                {% else %}
                     {{ form.email(class= "form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
        <div class="form-group">
        {{ form.submit( class="btn btn-outline-info bg-primary" ) }}
        </div>
    </form>
</div>
{% endblock content %}

blogapp/templates/single-post.html
{% extends 'layout.html' %}

{% block content %}

<!-- Home Section -->

<section id="home" class="main-single-post parallax-section">
     <div class="overlay"></div>
     <div class="container">
          <div class="row">

               <div class="col-md-12 col-sm-12">
                    <h1>Single Post</h1>
               </div>

          </div>
     </div>
</section>

<!-- Blog Single Post Section -->

<section id="blog-single-post">
    <div class="container">
         <div class="col-md-offset-1 col-md-10 col-sm-12">
                  <div class="blog-post-thumb">
<!--                         <div class="blog-post-image">-->
<!--                                  <img src="" class="img-responsive" alt="Blog Image">-->
<!--                         </div>-->
                         <div class="blog-post-format">
                              <span><a href="{{ url_for('users.user_posts', username=post.author.username) }}"><img src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}" class="img-responsive img-circle" style=" width: 55px;"> {{ post.author.username }}</a></span>
                              <span><i class="fa fa-date"></i> {{ post.date_posted.strftime( ' %d %b %Y') }}</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 35 </a></span>
                             <div class="blog-post-title">
                                  <h3>Title: {{ post.title }}</h3>
                             </div>
                         </div>
                         <div class="blog-post-des">
                              <p style="white-space: pre-wrap">{{post.content}}</p>
                         </div>
                      {% if post.author == current_user %}
                           <div>
                               <a class="btn btn-primary btn-sm m-2 " href="{{url_for('posts.update_post', post_id=post.id)}}"> Update </a>
                               <button type="button" class="btn btn-danger btn-sm m-2" data-toggle="modal" data-target="#deleteModal">Delete</button>
                           </div>
                      {% endif %}
                  </div>
          </div>
        </div>
</section>
<!-- Modal -->
     <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
       <div class="modal-dialog" role="document">
         <div class="modal-content">
           <div class="modal-header">
             <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
             </button>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
             <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST" style="display: inline-block">
                 <input class="btn-danger" type="submit" value="Delete">
             </form>
           </div>
         </div>
       </div>
     </div>

<!-- Footer Section -->

{% endblock content %}

blogapp/templates/user_post.html
{% extends "layout.html" %}

{% block content %}

<section id="blog">
    <div class="container">
            <div class="col-md-offset-1 col-md-10 col-sm-12">
                <h2 class="mb-3">Posts By {{user.username}} ({{ posts.total}}) </h2> <hr>
            </div>
    </div>
         {% for post in posts.items %}
    <div class="container">
         <div class="col-md-offset-1 col-md-10 col-sm-12">
                  <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a href="{{url_for('posts.single', post_id=post.id)}}">
                                  <img src="{{image_content}}" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="{{ url_for('posts.single', post_id=post.id)}}">{{ post.title }} </a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="{{ url_for('users.user_posts', username=post.author.username)}}"><img src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}" class="img-responsive img-circle" style=" width: 55px;"> {{ post.author.username }}</a></span>
                              <span><i class="fa fa-date"></i> {{ post.date_posted.strftime( ' %d %b %Y') }}</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 35 </a></span>
                         </div>
                         <div class="blog-post-des">
                              <p style="white-space: pre-wrap">{{post.content}}</p>
                              <a href="{{ url_for('posts.single',post_id=post.id)}}" class="btn btn-default">Continue Reading</a>
                         </div>
                  </div>
          </div>
        </div>

</section>


     {% endfor %}

     {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
               {% if posts.page == page_num %}
                   <a  class="btn btn-danger mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"> {{page_num}} </a>
               {% else %}
                   <a  class="btn btn-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"> {{page_num}} </a>
               {% endif %}
          {% else %}
               ...
          {% endif %}
     {% endfor %}
<!-- Footer Section -->

{% endblock content %}